title: SJTU MedIA
description: GitHub Pages local preview powered by Jekyll and Docker Compose.
repository: dengyushan/sjtu-media.github.io
markdown: kramdown
exclude:
  - vendor/
  - .bundle/
  - .docker-jekyll-cache/
  - .docker-sass-cache/
  - .docker-site/
  - .dockerignore
  - Dockerfile
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - README.md
  - docker-compose.yml
