# site properties and page defaults
title: SJTU MedIA
mobile-title: MedIA
subtitle: Medical Image Analysis Lab
description: Medical image analysis, computational imaging, and AI for healthcare at Shanghai Jiao Tong University.
header:
footer:
proofer: false
repository: sjtu-media/sjtu-media.github.io

# site social media and other links
links:
  github: sjtu-media

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_members_zh
  - scope:
      type: "members_zh"
    values:
      layout: member
  # markdown files in /_members_en
  - scope:
      type: "members_en"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  members_zh:
    output: true
    permalink: /zh/people/:slug/
  members_en:
    output: true
    permalink: /en/people/:slug/
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
  - docker-compose.yml
